
# 🧙‍♂️ vdclient Magic 使用教學

這份 Notebook 是為了協助 **第一次使用 vdclient magic 的使用者** 能夠快速上手。
vdclient magic 是一套支援多種 RDB 資料來源的查詢工具，特別設計給在 Jupyter Notebook 環境中進行互動式開發的資料科學家與分析師使用。

### %vdclient -h：說明vdclient使用方式

In [1]:
%vdclient -h

### 🪄[常見用法一] %%vdclient (grid): 顯示 SQL 語法前一千筆回傳結果，可用來確認 SQL 語法是否如預期

In [2]:
## 備註："insurance" 為在 DeepFlow 資料源連線管理上設定的「資料源名稱」

In [3]:
%%vdclient --datasource insurance
SELECT * FROM provider_data

HTML(value="<p style='font-size:18px'>🔍 顯示前 <code>1000</code> 筆資料</p>")

### 🪄[常見用法二] %%vdclient -v variable: 將 SQL 語法回傳結果存成 python dataframe，用來取用資料進行後續資料分析

In [4]:
%%vdclient -v data --datasource insurance
SELECT * FROM provider_data

VBox(children=(HBox(children=(Label(value='Processing :'), FloatProgress(value=0.0, bar_style='info'), Label(v…

HTML(value='<p style="font-size:16px">✅ 已儲存為變數：<code>data</code></p>')

In [5]:
print('shape:{}'.format(data.shape))
data.head()

shape:(555554, 20)

,claimid,patientid,age,provider,category,claim_start_dt,claim_end_dt,claim_days,admission_dt,discharge_dt,admission_days,attending_physician,operating_physician,other_physician,physicians,claim_admit_diagnosis_code,diagnosis_group_code,diagnosis_codes,insurance_claim_amt_reimbursed,deductible_amt_paid
0,CLM77153,BENE15971,65.0,PRS51031,inpatient,2009-11-22 16:00:00,2009-11-25 16:00:00,4.0,2009-11-22 16:00:00,2009-11-25 16:00:00,4.0,PHY409001,PHY427973,None,"PHY409001,PHY427973",4414,305,"4271,V4582,41400,32723,4240,60000,78820,V145,4...",24000.0,1068.0
1,CLM80211,BENE15996,88.0,PRS55232,inpatient,2009-12-18 16:00:00,2009-12-22 16:00:00,5.0,2009-12-18 16:00:00,2009-12-22 16:00:00,5.0,PHY365510,PHY324868,None,"PHY365510,PHY324868",81301,555,"81342,73300,42789,71590,3051,E8801,3331,4019,2...",6000.0,1068.0
2,CLM80329,BENE15997,72.0,PRS52076,inpatient,2009-12-19 16:00:00,2009-12-20 16:00:00,2.0,2009-12-19 16:00:00,2009-12-20 16:00:00,2.0,PHY333591,PHY413100,None,"PHY333591,PHY413100",71516,495,"71515,7140,42731,2752,2859",11000.0,1068.0
3,CLM78933,BENE16012,76.0,PRS51490,inpatient,2009-12-07 16:00:00,2009-12-08 16:00:00,2.0,2009-12-07 16:00:00,2009-12-08 16:00:00,2.0,PHY325912,None,None,PHY325912,78650,293,"42833,V1005,78079,42731,49392,79902,41400,4273...",5000.0,1068.0
4,CLM80878,BENE16040,72.0,PRS57317,inpatient,2009-12-25 16:00:00,2009-12-27 16:00:00,3.0,2009-12-25 16:00:00,2009-12-27 16:00:00,3.0,PHY325217,None,None,PHY325217,78650,229,"41401,4019,53081,V173,2724,42731,2859,30000,4271",4000.0,1068.0

### 🪄[常見用法三] %%vdclient -e file.parquet: 將 SQL 語法回傳結果存成 parquet 格式檔案，用於大量資料存取

In [6]:
%%vdclient -e "/tmp/test_postgres.parquet" --datasource insurance
SELECT * FROM provider_data

VBox(children=(HBox(children=(Label(value='Processing :'), FloatProgress(value=0.0, bar_style='info'), Label(v…

HTML(value='<p style="font-size:16px">✅ 已輸出檔案：<code>/tmp/test_postgres.parquet</code></p>')

In [7]:
import pandas as pd

df = pd.read_parquet("/tmp/test_postgres.parquet")

print('shape:{}'.format(df.shape))
df.head()

shape:(555554, 20)

,claimid,patientid,age,provider,category,claim_start_dt,claim_end_dt,claim_days,admission_dt,discharge_dt,admission_days,attending_physician,operating_physician,other_physician,physicians,claim_admit_diagnosis_code,diagnosis_group_code,diagnosis_codes,insurance_claim_amt_reimbursed,deductible_amt_paid
0,CLM77153,BENE15971,65.0,PRS51031,inpatient,2009-11-22 16:00:00+00:00,2009-11-25 16:00:00+00:00,4.0,2009-11-22 16:00:00+00:00,2009-11-25 16:00:00+00:00,4.0,PHY409001,PHY427973,None,"PHY409001,PHY427973",4414,305,"4271,V4582,41400,32723,4240,60000,78820,V145,4...",24000.0,1068.0
1,CLM80211,BENE15996,88.0,PRS55232,inpatient,2009-12-18 16:00:00+00:00,2009-12-22 16:00:00+00:00,5.0,2009-12-18 16:00:00+00:00,2009-12-22 16:00:00+00:00,5.0,PHY365510,PHY324868,None,"PHY365510,PHY324868",81301,555,"81342,73300,42789,71590,3051,E8801,3331,4019,2...",6000.0,1068.0
2,CLM80329,BENE15997,72.0,PRS52076,inpatient,2009-12-19 16:00:00+00:00,2009-12-20 16:00:00+00:00,2.0,2009-12-19 16:00:00+00:00,2009-12-20 16:00:00+00:00,2.0,PHY333591,PHY413100,None,"PHY333591,PHY413100",71516,495,"71515,7140,42731,2752,2859",11000.0,1068.0
3,CLM78933,BENE16012,76.0,PRS51490,inpatient,2009-12-07 16:00:00+00:00,2009-12-08 16:00:00+00:00,2.0,2009-12-07 16:00:00+00:00,2009-12-08 16:00:00+00:00,2.0,PHY325912,None,None,PHY325912,78650,293,"42833,V1005,78079,42731,49392,79902,41400,4273...",5000.0,1068.0
4,CLM80878,BENE16040,72.0,PRS57317,inpatient,2009-12-25 16:00:00+00:00,2009-12-27 16:00:00+00:00,3.0,2009-12-25 16:00:00+00:00,2009-12-27 16:00:00+00:00,3.0,PHY325217,None,None,PHY325217,78650,229,"41401,4019,53081,V173,2724,42731,2859,30000,4271",4000.0,1068.0

### 🪄[常見用法四] 支援動態參數傳遞

In [8]:
datasource = "insurance"
table ="provider_data"

In [9]:
%%vdclient --datasource {datasource}
SELECT * FROM {table}

HTML(value="<p style='font-size:18px'>🔍 顯示前 <code>1000</code> 筆資料</p>")