
# 🧙‍♂️ vdclient Magic SDK 使用教學
vdclient magic 除了可在 Jupyter Notebook 環境中使用，也可以透過 SDK 在 .py 程式內執行

In [1]:
import pandas as pd
import os
from vdclient_magic.core.sql import sql_to_df, sql_to_file

## 🪄 sql_to_df：將 SQL 語法回傳結果存成 python dataframe，用來取用資料進行後續資料分析

In [2]:
sql = "SELECT * FROM provider_data"
df = sql_to_df(sql, datasource="insurance", chunksize=200000) # insurance 為在 DeepFlow 資料源連線管理上設定的「資料源名稱」

print(f"✅ 合併後資料列數：{df.shape[0]}")
display(df.head())

VBox(children=(HBox(children=(Label(value='Processing :'), FloatProgress(value=0.0, bar_style='info'), Label(v…

✅ 合併後資料列數：555554

,claimid,patientid,age,provider,category,claim_start_dt,claim_end_dt,claim_days,admission_dt,discharge_dt,admission_days,attending_physician,operating_physician,other_physician,physicians,claim_admit_diagnosis_code,diagnosis_group_code,diagnosis_codes,insurance_claim_amt_reimbursed,deductible_amt_paid
0,CLM76844,BENE31354,69.0,PRS51435,inpatient,2009-11-20 16:00:00,2009-11-23 16:00:00,4.0,2009-11-20 16:00:00,2009-11-23 16:00:00,4.0,PHY316577,PHY387100,PHY347188,"PHY316577,PHY387100,PHY347188",1737,594,"9061,V5861,7140,53081,42731,4280,56400,3051,68...",10000.0,1068.0
1,CLM78075,BENE31361,54.0,PRS54258,inpatient,2009-11-30 16:00:00,2009-12-01 16:00:00,2.0,2009-11-30 16:00:00,2009-12-01 16:00:00,2.0,PHY351912,PHY431508,None,"PHY351912,PHY431508",99812,919,"99889,78863,27800,4240,25000,92411,55321,8261,...",6000.0,1068.0
2,CLM78076,BENE31364,75.0,PRS54653,inpatient,2009-11-30 16:00:00,2009-12-05 16:00:00,6.0,2009-11-30 16:00:00,2009-12-05 16:00:00,6.0,PHY407854,None,None,PHY407854,1912,086,"1983,25000,4019,41400,1540,5990",5000.0,1068.0
3,CLM77642,BENE31378,77.0,PRS51501,inpatient,2009-11-26 16:00:00,2009-12-04 16:00:00,9.0,2009-11-26 16:00:00,2009-12-04 16:00:00,9.0,PHY327234,None,None,PHY327234,V5789,946,"V5789,V4581,41072,725,7993,56210,73679,496,V5416",10000.0,1068.0
4,CLM80453,BENE31384,80.0,PRS57547,inpatient,2009-12-20 16:00:00,2009-12-22 16:00:00,3.0,2009-12-20 16:00:00,2009-12-22 16:00:00,3.0,PHY408517,PHY357869,None,"PHY408517,PHY357869",7213,552,72283,5000.0,1068.0

## 🪄 sql_to_file：將 SQL 語法回傳結果存成 parquet 格式檔案，用於大量資料存取

In [3]:
# 暫存 Parquet 檔案
filename = "/tmp/test_sql_output.parquet"
sql = "SELECT * FROM provider_data"

# 寫入
sql_to_file(sql, filename, datasource="insurance", chunksize=200000)

# 驗證讀回內容
if os.path.exists(filename):
    df = pd.read_parquet(filename)
    print(f"✅ 成功寫入 parquet，列數：{df.shape[0]}")
    display(df.head())
    os.remove(filename)
else:
    print("❌ 檔案寫入失敗")

VBox(children=(HBox(children=(Label(value='Processing :'), FloatProgress(value=0.0, bar_style='info'), Label(v…

✅ 成功寫入 parquet，列數：555554

,claimid,patientid,age,provider,category,claim_start_dt,claim_end_dt,claim_days,admission_dt,discharge_dt,admission_days,attending_physician,operating_physician,other_physician,physicians,claim_admit_diagnosis_code,diagnosis_group_code,diagnosis_codes,insurance_claim_amt_reimbursed,deductible_amt_paid
0,CLM76844,BENE31354,69.0,PRS51435,inpatient,2009-11-20 16:00:00+00:00,2009-11-23 16:00:00+00:00,4.0,2009-11-20 16:00:00+00:00,2009-11-23 16:00:00+00:00,4.0,PHY316577,PHY387100,PHY347188,"PHY316577,PHY387100,PHY347188",1737,594,"9061,V5861,7140,53081,42731,4280,56400,3051,68...",10000.0,1068.0
1,CLM78075,BENE31361,54.0,PRS54258,inpatient,2009-11-30 16:00:00+00:00,2009-12-01 16:00:00+00:00,2.0,2009-11-30 16:00:00+00:00,2009-12-01 16:00:00+00:00,2.0,PHY351912,PHY431508,None,"PHY351912,PHY431508",99812,919,"99889,78863,27800,4240,25000,92411,55321,8261,...",6000.0,1068.0
2,CLM78076,BENE31364,75.0,PRS54653,inpatient,2009-11-30 16:00:00+00:00,2009-12-05 16:00:00+00:00,6.0,2009-11-30 16:00:00+00:00,2009-12-05 16:00:00+00:00,6.0,PHY407854,None,None,PHY407854,1912,086,"1983,25000,4019,41400,1540,5990",5000.0,1068.0
3,CLM77642,BENE31378,77.0,PRS51501,inpatient,2009-11-26 16:00:00+00:00,2009-12-04 16:00:00+00:00,9.0,2009-11-26 16:00:00+00:00,2009-12-04 16:00:00+00:00,9.0,PHY327234,None,None,PHY327234,V5789,946,"V5789,V4581,41072,725,7993,56210,73679,496,V5416",10000.0,1068.0
4,CLM80453,BENE31384,80.0,PRS57547,inpatient,2009-12-20 16:00:00+00:00,2009-12-22 16:00:00+00:00,3.0,2009-12-20 16:00:00+00:00,2009-12-22 16:00:00+00:00,3.0,PHY408517,PHY357869,None,"PHY408517,PHY357869",7213,552,72283,5000.0,1068.0